name: apploook
description: "LOOOK Mobile Application"
publish_to: "none"

version: 1.5.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^5.0.0
  intl: 0.19.0
  cupertino_icons: ^1.0.6
  curved_navigation_bar: ^1.0.3
  transparent_image: ^2.0.1
  flutter_svg: ^2.0.10+1
  iconify: ^0.0.1
  url_launcher: ^6.0.9
  phone_form_field: ^9.2.3
  shared_preferences: ^2.2.3
  yandex_mapkit: ^4.0.2
  geolocator: ^12.0.0
  yandex_geocoder: ^2.3.1
  dio: ^5.4.3+1
  firebase_core: ^2.32.0
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^17.1.3
  carousel_slider: ^5.0.0
  flutter_image_compress: ^2.1.0

  visibility_detector: ^0.4.0+2
  firebase_remote_config: ^4.4.7
  cached_network_image: ^3.4.0
  firebase_auth: ^4.16.0
  video_player: ^2.9.2
  pin_code_fields: ^8.0.1
  http: ^1.3.0
  socket_io_client: ^3.1.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/videos/loader.mp4

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Italic.ttf
          style: italic
        - asset: fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/192x192.png"
  remove_alpha_ios: true
  