name: apploook
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  intl: 0.18.1
  cupertino_icons: ^1.0.6
  curved_navigation_bar: ^1.0.3
  transparent_image: ^2.0.1
  flutter_svg: ^2.0.10+1
  iconify: ^0.0.1
  url_launcher: ^6.0.9
  phone_form_field: ^9.2.3
  shared_preferences: ^2.2.3
  yandex_mapkit: ^4.0.2
  geolocator: ^12.0.0
  yandex_geocoder: ^2.3.1
  dio: ^5.4.3+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Italic.ttf
          style: italic
        - asset: fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/launchericon.png"
