// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZYRHBdJGMBmCg9l2O6uJye9oGhBhPkzE',
    appId: '1:87012829234:web:6cb4a8e9b41d30b688f42b',
    messagingSenderId: '87012829234',
    projectId: 'loookuz-37798',
    authDomain: 'loookuz-37798.firebaseapp.com',
    storageBucket: 'loookuz-37798.firebasestorage.app',
    measurementId: 'G-Z8RKHE9EKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr7NYaMJUkaNCPw0S_nkoArT_FkAjulXU',
    appId: '1:87012829234:android:348ec4482968cd6788f42b',
    messagingSenderId: '87012829234',
    projectId: 'loookuz-37798',
    storageBucket: 'loookuz-37798.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqd3W1eKCuzbanmvcdoUri9RyGCc62xfY',
    appId: '1:87012829234:ios:1d206bee1565cdc288f42b',
    messagingSenderId: '87012829234',
    projectId: 'loookuz-37798',
    storageBucket: 'loookuz-37798.firebasestorage.app',
    iosBundleId: 'com.loook.v1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqd3W1eKCuzbanmvcdoUri9RyGCc62xfY',
    appId: '1:87012829234:ios:65e028d30352fe8988f42b',
    messagingSenderId: '87012829234',
    projectId: 'loookuz-37798',
    storageBucket: 'loookuz-37798.firebasestorage.app',
    iosBundleId: 'com.example.apploook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZYRHBdJGMBmCg9l2O6uJye9oGhBhPkzE',
    appId: '1:87012829234:web:214ceebcba1c62f688f42b',
    messagingSenderId: '87012829234',
    projectId: 'loookuz-37798',
    authDomain: 'loookuz-37798.firebaseapp.com',
    storageBucket: 'loookuz-37798.firebasestorage.app',
    measurementId: 'G-H5S7YQC0DL',
  );

}