// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDMcNrGJ8YIbGFqneAK7Zk2pXOOqqF617Q',
//     appId: '1:35787525405:web:5471163f32714e1f2365f4',
//     messagingSenderId: '35787525405',
//     projectId: 'loook-2b9f8',
//     authDomain: 'loook-2b9f8.firebaseapp.com',
//     storageBucket: 'loook-2b9f8.appspot.com',
//     measurementId: 'G-0F2FKPZV3B',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDuQ1k-kDZZEZUYynSLQ_lG3ARsc27ophA',
//     appId: '1:35787525405:android:48f7fa65ec3add982365f4',
//     messagingSenderId: '35787525405',
//     projectId: 'loook-2b9f8',
//     storageBucket: 'loook-2b9f8.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDHIxZuGyFoUDcYOapNFBLWaupgNsNB2yg',
//     appId: '1:35787525405:ios:968ccbf13c0515a52365f4',
//     messagingSenderId: '35787525405',
//     projectId: 'loook-2b9f8',
//     storageBucket: 'loook-2b9f8.appspot.com',
//     iosBundleId: 'com.apploook.v1',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDHIxZuGyFoUDcYOapNFBLWaupgNsNB2yg',
//     appId: '1:35787525405:ios:cf40d7d9e29c11fd2365f4',
//     messagingSenderId: '35787525405',
//     projectId: 'loook-2b9f8',
//     storageBucket: 'loook-2b9f8.appspot.com',
//     iosBundleId: 'com.example.apploook',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyDMcNrGJ8YIbGFqneAK7Zk2pXOOqqF617Q',
//     appId: '1:35787525405:web:0f289c0a7f5a160b2365f4',
//     messagingSenderId: '35787525405',
//     projectId: 'loook-2b9f8',
//     authDomain: 'loook-2b9f8.firebaseapp.com',
//     storageBucket: 'loook-2b9f8.appspot.com',
//     measurementId: 'G-RX2ZK50QSZ',
//   );
// }
